import markdown

def generate_brand_book_html(brand_name, tov_text, personas_text, cjm_text):
    """
    Generates a styled HTML Brand Book from the provided Markdown content.
    """
    
    # Convert Markdown to HTML
    tov_html = markdown.markdown(tov_text)
    personas_html = markdown.markdown(personas_text)
    cjm_html = markdown.markdown(cjm_text, extensions=['tables'])

    html_template = f"""
    <!DOCTYPE html>
    <html lang="uk">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Brand Book: {brand_name}</title>
        <style>
            body {{
                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max_width: 800px;
                margin: 0 auto;
                padding: 40px;
                background-color: #f9f9f9;
            }}
            .container {{
                background-color: white;
                padding: 50px;
                box-shadow: 0 4px 15px rgba(0,0,0,0.1);
                border-radius: 8px;
            }}
            h1, h2, h3 {{
                color: #2c3e50;
            }}
            h1 {{
                text-align: center;
                font-size: 3em;
                margin-bottom: 10px;
                border-bottom: 2px solid #e74c3c;
                padding-bottom: 20px;
            }}
            .subtitle {{
                text-align: center;
                color: #7f8c8d;
                font-size: 1.2em;
                margin-bottom: 50px;
            }}
            h2 {{
                margin-top: 40px;
                border-bottom: 1px solid #eee;
                padding-bottom: 10px;
                color: #e74c3c;
            }}
            blockquote {{
                background: #f9f9f9;
                border-left: 5px solid #e74c3c;
                margin: 1.5em 10px;
                padding: 0.5em 10px;
                font-style: italic;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
            }}
            th, td {{
                border: 1px solid #ddd;
                padding: 12px;
                text-align: left;
            }}
            th {{
                background-color: #f2f2f2;
                font-weight: bold;
            }}
            tr:nth-child(even) {{
                background-color: #f9f9f9;
            }}
            .footer {{
                text-align: center;
                margin-top: 50px;
                font-size: 0.8em;
                color: #aaa;
            }}
            @media print {{
                body {{ background-color: white; }}
                .container {{ box-shadow: none; padding: 0; }}
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>{brand_name}</h1>
            <div class="subtitle">Brand Book & Strategy Guide</div>

            <div id="tov">
                {tov_html}
            </div>

            <div id="personas">
                <hr>
                {personas_html}
            </div>

            <div id="cjm">
                <hr>
                <h2>🗺️ Customer Journey Map</h2>
                {cjm_html}
            </div>

            <div class="footer">
                Generated by SEO Content Machine
            </div>
        </div>
    </body>
    </html>
    """
    return html_template
